pstv() {
	local p
	local rp=$(
		python <<-end
			import psutil as ps
			print(
				*sorted(
					p.pid for p in ps.process_iter(["ppid"]) if p.info["ppid"]==0
				)
			)
		end
	)

	for p in $rp; do
		echo "[$(cat /proc/$p/cgroup)]"
		pstree -planThS $p
	done
}
